version: '3.4'

x-common: &common
  environment: &common-environment
    TZ: Europe/Paris
  logging:
    driver: local
  restart: unless-stopped

services:
  mycv.rating.api.read:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_Kestrel__Certificates__Default__Password: test
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__SqlServerConnectionString: "Server=sqlserver;Database=Rating;User Id=sa;Password=Password123!,;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=False"
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  mycv.rating.api.write:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_Kestrel__Certificates__Default__Password: test
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__SqlServerConnectionString: "Server=sqlserver;Database=Rating;User Id=sa;Password=Password123!,;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=False"
    ports:
      - "5100:8080"
      - "5101:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
      
  sqlserver:
    environment:
      <<: *common-environment
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!,
    ports:
      - 1433:1433
    networks:
      - db
