//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCv.UI.Resources.Components.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Career {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Career() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCv.UI.Resources.Components.Pages.Career", typeof(Career).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baccalaureate.
        /// </summary>
        public static string EducationBaccalaureate {
            get {
                return ResourceManager.GetString("EducationBaccalaureate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering degree.
        /// </summary>
        public static string EducationEngineeringDegree {
            get {
                return ResourceManager.GetString("EducationEngineeringDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System, automation and vision engineering.
        /// </summary>
        public static string EducationEngineeringDegreeTitle {
            get {
                return ResourceManager.GetString("EducationEngineeringDegreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string EducationMaster {
            get {
                return ResourceManager.GetString("EducationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business administration.
        /// </summary>
        public static string EducationMasterBusinessTitle {
            get {
                return ResourceManager.GetString("EducationMasterBusinessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaging, medical and surgical robotics.
        /// </summary>
        public static string EducationMasterScienceTitle {
            get {
                return ResourceManager.GetString("EducationMasterScienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner of {0}.
        /// </summary>
        public static string EducationPartnerOf {
            get {
                return ResourceManager.GetString("EducationPartnerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked {0}.
        /// </summary>
        public static string EducationRanked {
            get {
                return ResourceManager.GetString("EducationRanked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}.
        /// </summary>
        public static string EducationScore {
            get {
                return ResourceManager.GetString("EducationScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With high honours.
        /// </summary>
        public static string EducationWithHighHonours {
            get {
                return ResourceManager.GetString("EducationWithHighHonours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering school.
        /// </summary>
        public static string EngineeringSchool {
            get {
                return ResourceManager.GetString("EngineeringSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strengths of my career:&lt;br /&gt;
        ///- a multidisciplinary mindset for an efficient collaboration with teams&lt;br /&gt;
        ///- an analytic skill to solve various problems in differents contexts&lt;br /&gt;
        ///- a continuous learning to guarantee a quality of work and a modern tools.
        /// </summary>
        public static string Highlights {
            get {
                return ResourceManager.GetString("Highlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My journey combines many domains (engineering, robotic surgery, business management...) and experience in both a major company and a dynamic startup environment..
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software engineer.
        /// </summary>
        public static string SectionExperienceCeaJobTitle {
            get {
                return ResourceManager.GetString("SectionExperienceCeaJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saclay (Paris), Île-de-France, France.
        /// </summary>
        public static string SectionExperienceCeaPlace {
            get {
                return ResourceManager.GetString("SectionExperienceCeaPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of a viewing and post-processing tool for radioactivity analysis..
        /// </summary>
        public static string SectionExperienceCeaProjectTitle {
            get {
                return ResourceManager.GetString("SectionExperienceCeaProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software engineer .NET.
        /// </summary>
        public static string SectionExperienceEiJobTitle {
            get {
                return ResourceManager.GetString("SectionExperienceEiJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strasbourg, Bas-Rhin, France.
        /// </summary>
        public static string SectionExperienceEiPlace {
            get {
                return ResourceManager.GetString("SectionExperienceEiPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecom applications development and support for Crédit Mutuel, CIC, Cofidis....
        /// </summary>
        public static string SectionExperienceEiProjectTitle {
            get {
                return ResourceManager.GetString("SectionExperienceEiProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategic marketing (internship).
        /// </summary>
        public static string SectionExperienceGeJobTitle {
            get {
                return ResourceManager.GetString("SectionExperienceGeJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vélizy-Villacoublay (Paris), Île-de-France, France.
        /// </summary>
        public static string SectionExperienceGePlace {
            get {
                return ResourceManager.GetString("SectionExperienceGePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth plan for an imaging device dedicated to cardiac scintigraphy..
        /// </summary>
        public static string SectionExperienceGeProjectTitle {
            get {
                return ResourceManager.GetString("SectionExperienceGeProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software engineer R&amp;D (internship).
        /// </summary>
        public static string SectionExperienceInriaJobTitle {
            get {
                return ResourceManager.GetString("SectionExperienceInriaJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villeneuve-d’Ascq, Nord, France.
        /// </summary>
        public static string SectionExperienceInriaPlace {
            get {
                return ResourceManager.GetString("SectionExperienceInriaPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of surgery simulation..
        /// </summary>
        public static string SectionExperienceInriaProjectTitle {
            get {
                return ResourceManager.GetString("SectionExperienceInriaProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software engineer C++ (internship).
        /// </summary>
        public static string SectionExperienceSiemensJobTitle {
            get {
                return ResourceManager.GetString("SectionExperienceSiemensJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuremberg, Allemagne.
        /// </summary>
        public static string SectionExperienceSiemensPlace {
            get {
                return ResourceManager.GetString("SectionExperienceSiemensPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration of Simulink models in PLCs..
        /// </summary>
        public static string SectionExperienceSiemensProjectTitle {
            get {
                return ResourceManager.GetString("SectionExperienceSiemensProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET developer in R&amp;D.
        /// </summary>
        public static string SectionExperienceSylepsJobTitle {
            get {
                return ResourceManager.GetString("SectionExperienceSylepsJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorient, Brittany, France.
        /// </summary>
        public static string SectionExperienceSylepsPlace {
            get {
                return ResourceManager.GetString("SectionExperienceSylepsPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software design and development of a solution of supervision of a fleet of robots..
        /// </summary>
        public static string SectionExperienceSylepsProject1Title {
            get {
                return ResourceManager.GetString("SectionExperienceSylepsProject1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of a tool pour handling and compiling PL/SQL code..
        /// </summary>
        public static string SectionExperienceSylepsProject2Title {
            get {
                return ResourceManager.GetString("SectionExperienceSylepsProject2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of a generic REST API for customer data purge..
        /// </summary>
        public static string SectionExperienceSylepsProject3Title {
            get {
                return ResourceManager.GetString("SectionExperienceSylepsProject3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET tech lead and architect.
        /// </summary>
        public static string SectionExperienceXcellaJobTitle {
            get {
                return ResourceManager.GetString("SectionExperienceXcellaJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmor-Plage, Brittany, France.
        /// </summary>
        public static string SectionExperienceXcellaPlace {
            get {
                return ResourceManager.GetString("SectionExperienceXcellaPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervision of a fleet of robots for the management of logistic flows (AS/RS).
        /// </summary>
        public static string SectionExperienceXcellaProjectTitle {
            get {
                return ResourceManager.GetString("SectionExperienceXcellaProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and development of the .NET ecosystem with a microservices architecture, with CQRS/event sourcing patterns, monitoring tools integration (Grafana, Loki, Prometheus...).
        /// </summary>
        public static string SectionExperienceXcellaTask1 {
            get {
                return ResourceManager.GetString("SectionExperienceXcellaTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product and technical decisions (collision avoidance, battery charging, path computation...).
        /// </summary>
        public static string SectionExperienceXcellaTask2 {
            get {
                return ResourceManager.GetString("SectionExperienceXcellaTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps administration, pipelines creation, environments setup.
        /// </summary>
        public static string SectionExperienceXcellaTask3 {
            get {
                return ResourceManager.GetString("SectionExperienceXcellaTask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhancement of developing process and spread of best practices in software teams.
        /// </summary>
        public static string SectionExperienceXcellaTask4 {
            get {
                return ResourceManager.GetString("SectionExperienceXcellaTask4", resourceCulture);
            }
        }
    }
}
