//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCv.UI.Resources.Components.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Coding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Coding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCv.UI.Resources.Components.Pages.Coding", typeof(Coding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying best practices guarantees a maintainable code, a good understanding for developers....
        /// </summary>
        public static string HeaderIntroduction {
            get {
                return ResourceManager.GetString("HeaderIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a tech lead :&lt;br /&gt;
        ///- I ensure that the best practices are applied (documentation, code review, oral sharing...)&lt;br /&gt;
        ///- I guarantee a high code coverage.
        /// </summary>
        public static string HeaderTechLead {
            get {
                return ResourceManager.GetString("HeaderTechLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is an extract of the Rating service ({0}) where a few principles are described..
        /// </summary>
        public static string SectionBestPracticesExample {
            get {
                return ResourceManager.GetString("SectionBestPracticesExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These guides can be tedious to  read for developers, so I can write a compact guide with the key points or the main errors encountered in code reviews..
        /// </summary>
        public static string SectionBestPracticesGuide {
            get {
                return ResourceManager.GetString("SectionBestPracticesGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a tech lead, I apply and share the good practices widely inspired from the Microsoft standards..
        /// </summary>
        public static string SectionBestPracticesIntroduction {
            get {
                return ResourceManager.GetString("SectionBestPracticesIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a good quality of comments of PRs, it can be nice to add links towards official documentation for example..
        /// </summary>
        public static string SectionBestPracticesPR {
            get {
                return ResourceManager.GetString("SectionBestPracticesPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I encourage and promote &lt;MudLink Href=&quot;https://refactoring.guru/design-patterns&quot;&gt;design patterns&lt;/MudLink&gt; which make the code readable and maintainable. On the other side, I discourage  people to write methods with hundred of lines..
        /// </summary>
        public static string SectionDesignPatternsIntroduction {
            get {
                return ResourceManager.GetString("SectionDesignPatternsIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bit heavier than unit tests, the functional tests enhance productivity. Test-containers is a simple option for launching Docker containers of the dependencies (SQL Server, RabbitMQ, etc.) using a web application factory..
        /// </summary>
        public static string SectionFunctionalTests {
            get {
                return ResourceManager.GetString("SectionFunctionalTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even if it&apos;s not very realistic, here is an example of the Git tree of this lonely project:.
        /// </summary>
        public static string SectionGitExample {
            get {
                return ResourceManager.GetString("SectionGitExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I appreciate Git flow with the &lt;MudLink Href=&quot;https://www.conventionalcommits.org/en/v1.0.0/&quot;&gt;Conventional Commits&lt;/MudLink&gt; specification for a good collaboration and mangement of developments. This also leverage the use of tools like  Semantic Release.
        ///- Team support on Git flow and conventions
        ///- Branch protection
        ///- Hook.
        /// </summary>
        public static string SectionGitIntroduction {
            get {
                return ResourceManager.GetString("SectionGitIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA principle (&lt;MudLink Href=&quot;&quot;&gt;SetRatingCommandHandler.cs&lt;/MudLink&gt;)...
        /// </summary>
        public static string SectionUnitTestsAAA {
            get {
                return ResourceManager.GetString("SectionUnitTestsAAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit tests are required in most of the developments. They guarantee non regression (after changing the code) et give test cases. A goal of 80% of code coverage is realistic if the SRP is applied (often the case with CQRS structure)..
        /// </summary>
        public static string SectionUnitTestsIntroduction {
            get {
                return ResourceManager.GetString("SectionUnitTestsIntroduction", resourceCulture);
            }
        }
    }
}
