//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCv.UI.Resources.Components.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Education {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Education() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCv.UI.Resources.Components.Pages.Education", typeof(Education).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifications.
        /// </summary>
        public static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baccalaureate.
        /// </summary>
        public static string EducationBaccalaureate {
            get {
                return ResourceManager.GetString("EducationBaccalaureate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering degree.
        /// </summary>
        public static string EducationEngineeringDegree {
            get {
                return ResourceManager.GetString("EducationEngineeringDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System, automation and vision engineering.
        /// </summary>
        public static string EducationEngineeringDegreeTitle {
            get {
                return ResourceManager.GetString("EducationEngineeringDegreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string EducationMaster {
            get {
                return ResourceManager.GetString("EducationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business administration.
        /// </summary>
        public static string EducationMasterBusinessTitle {
            get {
                return ResourceManager.GetString("EducationMasterBusinessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaging, medical and surgical robotics.
        /// </summary>
        public static string EducationMasterScienceTitle {
            get {
                return ResourceManager.GetString("EducationMasterScienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner of {0}.
        /// </summary>
        public static string EducationPartnerOf {
            get {
                return ResourceManager.GetString("EducationPartnerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked {0}.
        /// </summary>
        public static string EducationRanked {
            get {
                return ResourceManager.GetString("EducationRanked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}.
        /// </summary>
        public static string EducationScore {
            get {
                return ResourceManager.GetString("EducationScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With high honours.
        /// </summary>
        public static string EducationWithHighHonours {
            get {
                return ResourceManager.GetString("EducationWithHighHonours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering school.
        /// </summary>
        public static string EngineeringSchool {
            get {
                return ResourceManager.GetString("EngineeringSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strengths of my journey: a multidisciplinary mindset for an efficient collaboration with teams, an analytic skill to solve various problems in differents contexts and a continuous learning to guarantee a quality of work and a modern tools.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
    }
}
