//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCv.UI.Wasm.Resources.Components.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Architecture {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Architecture() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCv.UI.Wasm.Resources.Components.Pages.Architecture", typeof(Architecture).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the architecture of the website you&apos;re browsing on..
        /// </summary>
        public static string ArchitectureIntroduction {
            get {
                return ResourceManager.GetString("ArchitectureIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What I can offer:.
        /// </summary>
        public static string ArchitectureMe1 {
            get {
                return ResourceManager.GetString("ArchitectureMe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - a design based on popular sources in accordance with the project&apos;s constraints.
        /// </summary>
        public static string ArchitectureMe2 {
            get {
                return ResourceManager.GetString("ArchitectureMe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - a CQRS &amp; event sourcing expertise.
        /// </summary>
        public static string ArchitectureMe3 {
            get {
                return ResourceManager.GetString("ArchitectureMe3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an app based on microservices where two domain-driven design (DDD) patterns are implemented: Command and Query Responsibility Segregation (CQRS) et event sourcing..
        /// </summary>
        public static string ArchitectureMicroservice {
            get {
                return ResourceManager.GetString("ArchitectureMicroservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is inspired from many references like.
        /// </summary>
        public static string ArchitectureReference1 {
            get {
                return ResourceManager.GetString("ArchitectureReference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Microsoft) or blogs like those from.
        /// </summary>
        public static string ArchitectureReference2 {
            get {
                return ResourceManager.GetString("ArchitectureReference2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the command.
        /// </summary>
        public static string CommandCommandStep {
            get {
                return ResourceManager.GetString("CommandCommandStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple rules validation: mark value between 0 and 5..
        /// </summary>
        public static string CommandCommandStepValidation {
            get {
                return ResourceManager.GetString("CommandCommandStepValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the aggregate.
        /// </summary>
        public static string CommandDomainStep {
            get {
                return ResourceManager.GetString("CommandDomainStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business rules validation: the profile is recommended but the mark is below 3..
        /// </summary>
        public static string CommandDomainStepValidation {
            get {
                return ResourceManager.GetString("CommandDomainStepValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate saving.
        /// </summary>
        public static string CommandSaveStep {
            get {
                return ResourceManager.GetString("CommandSaveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see the queries now!.
        /// </summary>
        public static string CommandSaveStepValidation {
            get {
                return ResourceManager.GetString("CommandSaveStepValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sequence diagram is a simplification of the writing process..
        /// </summary>
        public static string CommandsDescription {
            get {
                return ResourceManager.GetString("CommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST request sending.
        /// </summary>
        public static string CommandSendStep {
            get {
                return ResourceManager.GetString("CommandSendStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-end validation of the form: required recommendation&apos;s field..
        /// </summary>
        public static string CommandSendStepValidation {
            get {
                return ResourceManager.GetString("CommandSendStepValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start by creating a command to add a rate about the website:.
        /// </summary>
        public static string CommandsExample {
            get {
                return ResourceManager.GetString("CommandsExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you recommend my profile?.
        /// </summary>
        public static string CommandsRecommendation {
            get {
                return ResourceManager.GetString("CommandsRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much are you satisfied?.
        /// </summary>
        public static string CommandsSatisfaction {
            get {
                return ResourceManager.GetString("CommandsSatisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This concept has many advantages: maintenance (responsibility segregation), scalability of read and write, performance of read operations, command validation and business rules respect....
        /// </summary>
        public static string CQRSBenefits {
            get {
                return ResourceManager.GetString("CQRSBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CQRS is an architecture pattern where queries (&quot;read&quot;) and commands (&quot;write&quot;) are separated..
        /// </summary>
        public static string CQRSDefinition {
            get {
                return ResourceManager.GetString("CQRSDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sequence diagram is a simplification of the write process then the read process triggered by REST queries..
        /// </summary>
        public static string CQRSDiagram {
            get {
                return ResourceManager.GetString("CQRSDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s better than a practical example? Here we go!.
        /// </summary>
        public static string CQRSExample {
            get {
                return ResourceManager.GetString("CQRSExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, the &quot;Rating&quot; service applies CQRS to handle the scores of the visitors of this website..
        /// </summary>
        public static string CQRSService {
            get {
                return ResourceManager.GetString("CQRSService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It gives a complete history, ease the debugging and temporal requests, and can rebuild the state of the system..
        /// </summary>
        public static string EventSourcingBenefits {
            get {
                return ResourceManager.GetString("EventSourcingBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event sourcing is a pattern where state changes are saved like a sequence of immutable events rather than changing the current state directly. A very concrete example is a .
        /// </summary>
        public static string EventSourcingDefinition1 {
            get {
                return ResourceManager.GetString("EventSourcingDefinition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  where the current state would be the result of all the moves of the players (events)..
        /// </summary>
        public static string EventSourcingDefinition2 {
            get {
                return ResourceManager.GetString("EventSourcingDefinition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chess game.
        /// </summary>
        public static string EventSourcingDefinitionLink {
            get {
                return ResourceManager.GetString("EventSourcingDefinitionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The read database is updated on each event to compute the 3 top reasons which make you read this:.
        /// </summary>
        public static string EventSourcingReadResult {
            get {
                return ResourceManager.GetString("EventSourcingReadResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, the &quot;Insight&quot; service applies CQRS + event sourcing to handle what you expect from my profile and why you are on this website..
        /// </summary>
        public static string EventSourcingService {
            get {
                return ResourceManager.GetString("EventSourcingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every event is store in an append-only database..
        /// </summary>
        public static string EventSourcingWrite {
            get {
                return ResourceManager.GetString("EventSourcingWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why it&apos;s great? Because the current state is known but you can also replay all the events or get the state at a specific moment..
        /// </summary>
        public static string EventSourcingWriteBenefits {
            get {
                return ResourceManager.GetString("EventSourcingWriteBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see what it means with this example:.
        /// </summary>
        public static string EventSourcingWriteExample {
            get {
                return ResourceManager.GetString("EventSourcingWriteExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one or more reasons that lead you here, drop them in the zone and order them by pertinence:.
        /// </summary>
        public static string EventSourcingWriteExampleInstructions {
            get {
                return ResourceManager.GetString("EventSourcingWriteExampleInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the result in the event store:.
        /// </summary>
        public static string EventSourcingWriteExampleResult {
            get {
                return ResourceManager.GetString("EventSourcingWriteExampleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is useful whatever the field is: what were the treatments of a patient? How where the state of the drones before they crashed? What did the player when the bug happened?....
        /// </summary>
        public static string EventSourcingWriteIllustration {
            get {
                return ResourceManager.GetString("EventSourcingWriteIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intent.
        /// </summary>
        public static string Intent {
            get {
                return ResourceManager.GetString("Intent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting bored.
        /// </summary>
        public static string IntentBoredom {
            get {
                return ResourceManager.GetString("IntentBoredom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing time (no offense!).
        /// </summary>
        public static string IntentBoredomDescription {
            get {
                return ResourceManager.GetString("IntentBoredomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing.
        /// </summary>
        public static string IntentBrowsing {
            get {
                return ResourceManager.GetString("IntentBrowsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing tech portfolios.
        /// </summary>
        public static string IntentBrowsingDescription {
            get {
                return ResourceManager.GetString("IntentBrowsingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaboration.
        /// </summary>
        public static string IntentCollaboration {
            get {
                return ResourceManager.GetString("IntentCollaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for collaboration.
        /// </summary>
        public static string IntentCollaborationDescription {
            get {
                return ResourceManager.GetString("IntentCollaborationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curious.
        /// </summary>
        public static string IntentCurious {
            get {
                return ResourceManager.GetString("IntentCurious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curious about your work.
        /// </summary>
        public static string IntentCuriousDescription {
            get {
                return ResourceManager.GetString("IntentCuriousDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelance hunting.
        /// </summary>
        public static string IntentFreelance {
            get {
                return ResourceManager.GetString("IntentFreelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for contractors/freelancers.
        /// </summary>
        public static string IntentFreelanceDescription {
            get {
                return ResourceManager.GetString("IntentFreelanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping.
        /// </summary>
        public static string IntentHelping {
            get {
                return ResourceManager.GetString("IntentHelping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping Valérian for free because I&apos;m nice.
        /// </summary>
        public static string IntentHelpingDescription {
            get {
                return ResourceManager.GetString("IntentHelpingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misclick.
        /// </summary>
        public static string IntentMisclick {
            get {
                return ResourceManager.GetString("IntentMisclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I misclicked!.
        /// </summary>
        public static string IntentMisclickDescription {
            get {
                return ResourceManager.GetString("IntentMisclickDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        public static string IntentNetworking {
            get {
                return ResourceManager.GetString("IntentNetworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        public static string IntentNetworkingDescription {
            get {
                return ResourceManager.GetString("IntentNetworkingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following up.
        /// </summary>
        public static string IntentPost {
            get {
                return ResourceManager.GetString("IntentPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following up after a talk/post.
        /// </summary>
        public static string IntentPostDescription {
            get {
                return ResourceManager.GetString("IntentPostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiting.
        /// </summary>
        public static string IntentRecruiting {
            get {
                return ResourceManager.GetString("IntentRecruiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiting / Hiring.
        /// </summary>
        public static string IntentRecruitingDescription {
            get {
                return ResourceManager.GetString("IntentRecruitingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        public static string IntentReputation {
            get {
                return ResourceManager.GetString("IntentReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heard about you.
        /// </summary>
        public static string IntentReputationDescription {
            get {
                return ResourceManager.GetString("IntentReputationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewing.
        /// </summary>
        public static string IntentReviewing {
            get {
                return ResourceManager.GetString("IntentReviewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewing your resume.
        /// </summary>
        public static string IntentReviewingDescription {
            get {
                return ResourceManager.GetString("IntentReviewingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microservice.
        /// </summary>
        public static string Microservice {
            get {
                return ResourceManager.GetString("Microservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A gateway (YARP) to avoid a direct access and coupling the services with the interface..
        /// </summary>
        public static string MicroserviceAPI {
            get {
                return ResourceManager.GetString("MicroserviceAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This avoids coupling the services with the interface and also secure the app with a single entrypoint..
        /// </summary>
        public static string MicroserviceAPIContent {
            get {
                return ResourceManager.GetString("MicroserviceAPIContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two microservices which communicate with RabbitMQ and use their own databases (EventStoreDB, MongoDB)..
        /// </summary>
        public static string MicroserviceBackend {
            get {
                return ResourceManager.GetString("MicroserviceBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two microservices which communicate with RabbitMQ and use their own databases (EventStoreDB, MongoDB)..
        /// </summary>
        public static string MicroserviceBackendContent {
            get {
                return ResourceManager.GetString("MicroserviceBackendContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a short description of the architecture of this project:.
        /// </summary>
        public static string MicroserviceDescription {
            get {
                return ResourceManager.GetString("MicroserviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The apps are containerized with Docker and launched through Docker Compose..
        /// </summary>
        public static string MicroserviceDocker {
            get {
                return ResourceManager.GetString("MicroserviceDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user interface developed with Blazor Server and MudBlazor..
        /// </summary>
        public static string MicroserviceFrontend {
            get {
                return ResourceManager.GetString("MicroserviceFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m also comfortable with Bootstrap and I&apos;ve done a ReactJS website..
        /// </summary>
        public static string MicroserviceFrontendContent {
            get {
                return ResourceManager.GetString("MicroserviceFrontendContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My developments are widely inspired from this Microsoft guide which helped me to understand and implement microservices apps:.
        /// </summary>
        public static string MicroserviceReference {
            get {
                return ResourceManager.GetString("MicroserviceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see now the last scores:.
        /// </summary>
        public static string QueriesExample {
            get {
                return ResourceManager.GetString("QueriesExample", resourceCulture);
            }
        }
    }
}
