//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCv.UI.Wasm.Resources.Components.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCv.UI.Wasm.Resources.Components.Pages.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional technologies.
        /// </summary>
        public static string AdditionalTechnologies {
            get {
                return ResourceManager.GetString("AdditionalTechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI/CD &amp; monitoring.
        /// </summary>
        public static string CICDAndMonitoring {
            get {
                return ResourceManager.GetString("CICDAndMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core expertise.
        /// </summary>
        public static string CoreExpertise {
            get {
                return ResourceManager.GetString("CoreExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core technology expertise.
        /// </summary>
        public static string CoreTechnologyExpertise {
            get {
                return ResourceManager.GetString("CoreTechnologyExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education and career.
        /// </summary>
        public static string EducationAndCareer {
            get {
                return ResourceManager.GetString("EducationAndCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Engineering degree,&lt;br /&gt;
        ///• Master&apos;s degree in surgical robotics,&lt;br /&gt;
        ///• Master&apos;s degree in business administration...&lt;br /&gt;
        ///Come and discover my training..
        /// </summary>
        public static string EducationAndCareerCaption {
            get {
                return ResourceManager.GetString("EducationAndCareerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond technical skills—explore my career journey and academic background.
        /// </summary>
        public static string EducationAndCareerCaptionSinglePage {
            get {
                return ResourceManager.GetString("EducationAndCareerCaptionSinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi. I&apos;m .
        /// </summary>
        public static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome on this resume website which is also a live demo of my skills (Blazor C#/.NET, Azure deployment, etc.)..
        /// </summary>
        public static string HomeIntroduction {
            get {
                return ResourceManager.GetString("HomeIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to consult the source code on.
        /// </summary>
        public static string HomeSourceCode {
            get {
                return ResourceManager.GetString("HomeSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about me.
        /// </summary>
        public static string MoreAboutMe {
            get {
                return ResourceManager.GetString("MoreAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond technical skills—explore my career journey, academic background, and personal interests.
        /// </summary>
        public static string MoreAboutMeCaption {
            get {
                return ResourceManager.GetString("MoreAboutMeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal life.
        /// </summary>
        public static string PersonalLife {
            get {
                return ResourceManager.GetString("PersonalLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond the code.
        /// </summary>
        public static string PersonalLifeCaption {
            get {
                return ResourceManager.GetString("PersonalLifeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalable system design.
        /// </summary>
        public static string ScalableSystemDesign {
            get {
                return ResourceManager.GetString("ScalableSystemDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills &amp; Expertise.
        /// </summary>
        public static string SkillsAndExpertise {
            get {
                return ResourceManager.GetString("SkillsAndExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive technical skills and leadership experience in modern software development.
        /// </summary>
        public static string SkillsCaption {
            get {
                return ResourceManager.GetString("SkillsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team management.
        /// </summary>
        public static string TeamManagement {
            get {
                return ResourceManager.GetString("TeamManagement", resourceCulture);
            }
        }
    }
}
