//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCv.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCv.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        public static string Architecture {
            get {
                return ResourceManager.GetString("Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclusion.
        /// </summary>
        public static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        public static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        public static string Experiences {
            get {
                return ResourceManager.GetString("Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi. I&apos;m Valérian..
        /// </summary>
        public static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome on this minimal and interactive resume which applies DDD with CQRS and event sourcing in C#/.NET..
        /// </summary>
        public static string HomeIntroduction {
            get {
                return ResourceManager.GetString("HomeIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to consult the source code on.
        /// </summary>
        public static string HomeSourceCode {
            get {
                return ResourceManager.GetString("HomeSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start.
        /// </summary>
        public static string HomeStart {
            get {
                return ResourceManager.GetString("HomeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting bored.
        /// </summary>
        public static string IntentBoredom {
            get {
                return ResourceManager.GetString("IntentBoredom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing time (no offense!).
        /// </summary>
        public static string IntentBoredomDescription {
            get {
                return ResourceManager.GetString("IntentBoredomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing.
        /// </summary>
        public static string IntentBrowsing {
            get {
                return ResourceManager.GetString("IntentBrowsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing tech portfolios.
        /// </summary>
        public static string IntentBrowsingDescription {
            get {
                return ResourceManager.GetString("IntentBrowsingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaboration.
        /// </summary>
        public static string IntentCollaboration {
            get {
                return ResourceManager.GetString("IntentCollaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for collaboration.
        /// </summary>
        public static string IntentCollaborationDescription {
            get {
                return ResourceManager.GetString("IntentCollaborationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curious.
        /// </summary>
        public static string IntentCurious {
            get {
                return ResourceManager.GetString("IntentCurious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curious about your work.
        /// </summary>
        public static string IntentCuriousDescription {
            get {
                return ResourceManager.GetString("IntentCuriousDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelance hunting.
        /// </summary>
        public static string IntentFreelance {
            get {
                return ResourceManager.GetString("IntentFreelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for contractors/freelancers.
        /// </summary>
        public static string IntentFreelanceDescription {
            get {
                return ResourceManager.GetString("IntentFreelanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping.
        /// </summary>
        public static string IntentHelping {
            get {
                return ResourceManager.GetString("IntentHelping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping Valérian for free because I&apos;m nice.
        /// </summary>
        public static string IntentHelpingDescription {
            get {
                return ResourceManager.GetString("IntentHelpingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misclick.
        /// </summary>
        public static string IntentMisclick {
            get {
                return ResourceManager.GetString("IntentMisclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I misclicked!.
        /// </summary>
        public static string IntentMisclickDescription {
            get {
                return ResourceManager.GetString("IntentMisclickDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        public static string IntentNetworking {
            get {
                return ResourceManager.GetString("IntentNetworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        public static string IntentNetworkingDescription {
            get {
                return ResourceManager.GetString("IntentNetworkingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following up.
        /// </summary>
        public static string IntentPost {
            get {
                return ResourceManager.GetString("IntentPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following up after a talk/post.
        /// </summary>
        public static string IntentPostDescription {
            get {
                return ResourceManager.GetString("IntentPostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiting.
        /// </summary>
        public static string IntentRecruiting {
            get {
                return ResourceManager.GetString("IntentRecruiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiting / Hiring.
        /// </summary>
        public static string IntentRecruitingDescription {
            get {
                return ResourceManager.GetString("IntentRecruitingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        public static string IntentReputation {
            get {
                return ResourceManager.GetString("IntentReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heard about you.
        /// </summary>
        public static string IntentReputationDescription {
            get {
                return ResourceManager.GetString("IntentReputationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewing.
        /// </summary>
        public static string IntentReviewing {
            get {
                return ResourceManager.GetString("IntentReviewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewing your resume.
        /// </summary>
        public static string IntentReviewingDescription {
            get {
                return ResourceManager.GetString("IntentReviewingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microservice.
        /// </summary>
        public static string Microservice {
            get {
                return ResourceManager.GetString("Microservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal life.
        /// </summary>
        public static string PersonalLife {
            get {
                return ResourceManager.GetString("PersonalLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
    }
}
